import type { CaskBundle } from "./types.js";

export function buildSampleBundle(now = new Date()): CaskBundle {
  const createdAt = now.toISOString();
  const expiresAt = new Date(now.getTime() + 5 * 60 * 1000).toISOString();

  return {
    id: "bundle-demo-001",
    missionId: "mission-hackathon-demo",
    sourceNodeId: "altiair-hub",
    createdAt,
    filteringDecision: "review_policy",
    priority: 86,
    sensorEvents: [
      {
        id: "rfid-demo-001",
        kind: "rfid",
        sourceNodeId: "altiair-node-a",
        observedAt: createdAt,
        receivedAt: createdAt,
        zoneId: "training-zone-alpha",
        confidence: 0.64,
        policyState: "review_needed",
        readerId: "rfid-reader-a",
        tagId: "training-tag-001",
        antennaId: "antenna-a",
        rssi: -48,
        readCount: 4,
      },
      {
        id: "provider-style-loc-demo-001",
        kind: "provider_style_location",
        sourceNodeId: "altiair-node-a",
        observedAt: createdAt,
        receivedAt: createdAt,
        zoneId: "training-zone-alpha",
        confidence: 0.62,
        policyState: "review_needed",
        sourceType: "rfid_provider_style",
        sourceId: "arduino-rfid-kit-a",
        entityId: "training-tag-001",
        precisionRadiusMeters: 35,
        expiresAt,
        supportingEvidenceIds: ["rfid-demo-001"],
        isCarrierGrade: false,
      },
      {
        id: "camera-demo-001",
        kind: "camera",
        sourceNodeId: "altiair-orin",
        observedAt: createdAt,
        receivedAt: createdAt,
        zoneId: "training-zone-alpha",
        confidence: 0.57,
        policyState: "review_needed",
        cameraId: "orin-camera-vision",
        detectionClass: "authorized_training_drone_marker",
        retentionPolicy: "thumbnail_allowed",
        thumbnailRef: "local://media/thumbnails/camera-demo-001.jpg",
      },
      {
        id: "audio-demo-001",
        kind: "audio",
        sourceNodeId: "altiair-node-b",
        observedAt: createdAt,
        receivedAt: createdAt,
        zoneId: "training-zone-alpha",
        confidence: 0.46,
        policyState: "review_needed",
        microphoneId: "usb-mic-b",
        vadWindowMs: [0, 3200],
        acousticClass: "small_rotor_noise",
        asrConfidence: 0.0,
      },
    ],
    locationFixes: [
      {
        id: "locfix-demo-001",
        entityId: "training-tag-001",
        sourceType: "rfid_provider_style",
        sourceIds: ["provider-style-loc-demo-001"],
        zoneId: "training-zone-alpha",
        precisionRadiusMeters: 35,
        confidence: 0.62,
        observedAt: createdAt,
        expiresAt,
        isCarrierGrade: false,
        supportingEvidenceIds: ["rfid-demo-001", "provider-style-loc-demo-001"],
        policyState: "review_needed",
      },
    ],
    droneObservations: [
      {
        id: "drone-demo-001",
        sourceNodeId: "altiair-orin",
        droneClass: "commercial_quadcopter",
        zoneId: "training-zone-alpha",
        confidence: 0.57,
        mediaRef: "local://media/thumbnails/camera-demo-001.jpg",
        observedAt: createdAt,
        supportingEvidenceIds: ["camera-demo-001", "audio-demo-001"],
        policyState: "review_needed",
      },
    ],
    controlSourceEstimates: [
      {
        id: "control-demo-001",
        droneObservationIds: ["drone-demo-001"],
        estimatedZoneId: "training-zone-alpha",
        confidenceRingMeters: 75,
        confidence: 0.76,
        freshnessSeconds: 30,
        supportingEvidenceIds: ["rfid-demo-001", "provider-style-loc-demo-001", "audio-demo-001", "drone-demo-001"],
        contradictingEvidenceIds: [],
        policyState: "review_needed",
      },
    ],
    counterUasCues: [
      {
        id: "cue-demo-001",
        droneObservationIds: ["drone-demo-001"],
        controlSourceEstimateId: "control-demo-001",
        evidence: [
          {
            id: "drone-demo-001",
            kind: "drone_observation",
            summary: "Jetson visual inference identifies an authorized training drone marker in the training zone.",
          },
          {
            id: "locfix-demo-001",
            kind: "location_fix",
            summary: "RFID-derived provider-style fix places the tagged training subject in the same coarse zone.",
          },
          {
            id: "control-demo-001",
            kind: "control_source_estimate",
            summary: "Pi 5 hub correlates cached mission context with RFID, audio, and visual evidence.",
          },
        ],
        confidence: 0.76,
        policyGate: "review_needed",
        acknowledgementState: "queued",
        recommendedNextChecks: [
          "Confirm the cue with a second visual observation or operator report.",
          "Check whether the RFID read is stale before sharing beyond the local mesh.",
          "Keep the cue in human review until policy state changes.",
        ],
        createdAt,
        updatedAt: createdAt,
      },
    ],
    nodeHealth: [
      {
        nodeId: "altiair-hub",
        nodeRole: "pi5_hub",
        observedAt: createdAt,
        peerCount: 2,
        queueDepth: 1,
        cpuLoad: 0.42,
        memoryUsedMb: 1180,
        networkReachable: true,
        foundryReachable: false,
        modelStatus: "ready",
      },
      {
        nodeId: "altiair-node-a",
        nodeRole: "pi4_edge",
        observedAt: createdAt,
        peerCount: 3,
        queueDepth: 1,
        cpuLoad: 0.31,
        memoryUsedMb: 760,
        networkReachable: true,
        foundryReachable: false,
        modelStatus: "ready",
      },
      {
        nodeId: "altiair-node-b",
        nodeRole: "pi4_edge",
        observedAt: createdAt,
        peerCount: 3,
        queueDepth: 1,
        cpuLoad: 0.36,
        memoryUsedMb: 820,
        networkReachable: true,
        foundryReachable: false,
        modelStatus: "ready",
      },
      {
        nodeId: "altiair-orin",
        nodeRole: "jetson_orin_inference",
        observedAt: createdAt,
        peerCount: 3,
        queueDepth: 1,
        cpuLoad: 0.48,
        memoryUsedMb: 2048,
        networkReachable: true,
        foundryReachable: false,
        modelStatus: "ready",
      },
    ],
  };
}
