import type { MeshTopology, PeerObservation } from "./types.js";

export const defaultDdilMeshTopology: MeshTopology = {
  missionNetworkId: "altiair-ddil-demo-net",
  overlayCidr: "10.77.0.0/24",
  defaultApSsid: "Altiair-LAN",
  defaultLanCidr: "192.168.42.0/24",
  defaultGatewayAddress: "192.168.42.10",
  underlayCells: [
    {
      id: "pi5-demo-mission-lan",
      role: "demo_mission_lan",
      hostNodeId: "altiair-hub",
      ssid: "Altiair-LAN",
      cidr: "192.168.42.0/24",
      gatewayAddress: "192.168.42.10",
      preferredLinkClass: "wifi_ap",
      purpose: "Hackathon physical baseline: Pi 5 hosts the private local LAN and the Pi 4Bs plus Jetson join it.",
    },
    {
      id: "field-drone-lan-template",
      role: "field_drone_lan",
      preferredLinkClass: "wifi_ap",
      purpose: "Field pattern: a drone or drone-support payload may host or join a local LAN cell; overlay identity and ledger replication remain the app contract.",
    },
    {
      id: "field-hawkeye-lan-template",
      role: "field_vehicle_or_hawkeye_lan",
      preferredLinkClass: "ethernet",
      purpose: "Field pattern: Hawkeye, vehicle, or operator compute can host or bridge a local network cell when that underlay fits the deployment.",
    },
  ],
  transports: [
    "loopback_emulation",
    "direct_ethernet",
    "closed_lan",
    "wireguard_l3_overlay",
    "http_json_api",
    "store_forward_queue",
    "nats_jetstream_optional",
    "vendor_adapter_optional",
  ],
  interopBoundaries: [
    "foundry_osdk",
    "cjadc2_cop_optional",
    "cot_xml_optional",
    "lattice_style_entity_optional",
    "atak_tak_server_optional",
  ],
  policy: {
    zeroTrust: true,
    allowAutonomousAction: false,
    allowTargetProsecution: false,
    requireHumanAcknowledgementForCues: true,
    externalSharePolicy: "policy_gate_required",
    maxClockSkewSeconds: 2,
    maxBundleSizeBytes: 8 * 1024 * 1024,
    highWaterQueueDepth: 250,
    replication: {
      mode: "all_reachable_nodes",
      requiredRecordKinds: [
        "sensor_event",
        "location_fix",
        "drone_observation",
        "control_source_estimate",
        "counter_uas_cue",
        "node_health",
        "peer_intent",
        "training_tag_plan",
        "bundle_manifest",
      ],
      rawMediaStrategy: "metadata_hash_and_policy_allowed_blobs",
      encryptedAtRest: true,
      signedRecords: true,
      requirePeerAck: true,
      minSurvivorCopies: 2,
    },
  },
  nodes: [
    {
      id: "altiair-hub",
      hostname: "altiair-hub",
      platform: "raspberry_pi_5",
      roles: ["mesh_hub", "operator_display", "foundry_gateway"],
      lanAddress: "192.168.42.10",
      overlayAddress: "10.77.0.10",
      apiPort: 8080,
      wireGuardListenPort: 51820,
      publicKeyEnv: "ALTIAIR_HUB_WG_PUBLIC_KEY",
      preferredLinks: ["wifi_ap", "ethernet", "wireguard_overlay"],
      capabilities: [
        {
          name: "durable_queue",
          detail: "Primary SQLite queue owner and WebSocket fanout for the operator display.",
        },
        {
          name: "local_llm",
          detail: "Pi 5 class text triage and insight drafts for compact evidence bundles.",
        },
        {
          name: "foundry_sync",
          detail: "Preferred CASK/Foundry OSDK upload gateway when policy and uplink allow it.",
        },
      ],
      constraints: [
        "Create the Altiair-LAN private Wi-Fi AP for the day-one physical mission LAN.",
        "Do not make the hub a single point of failure; edge nodes keep local queues.",
        "Throttle media first when queue depth or CPU pressure rises.",
      ],
      gatewayPriority: 30,
    },
    {
      id: "altiair-node-a",
      hostname: "altiair-node-a",
      platform: "raspberry_pi_4b",
      roles: ["edge_sensor"],
      lanAddress: "192.168.42.11",
      overlayAddress: "10.77.0.11",
      apiPort: 8080,
      wireGuardListenPort: 51820,
      publicKeyEnv: "ALTIAIR_NODE_A_WG_PUBLIC_KEY",
      preferredLinks: ["wifi_ap", "wireguard_overlay", "ethernet"],
      capabilities: [
        {
          name: "sensor_ingest",
          detail: "Camera, microphone, RFID, and mock provider-style location bundles.",
        },
        {
          name: "local_filter",
          detail: "Deterministic or small-model bundle triage before forwarding.",
        },
      ],
      constraints: [
        "Keep bulky media local unless policy and congestion state allow transfer.",
        "Prefer metadata, thumbnails, and short transcripts over raw streams.",
      ],
      gatewayPriority: 5,
    },
    {
      id: "altiair-node-b",
      hostname: "altiair-node-b",
      platform: "raspberry_pi_4b",
      roles: ["edge_sensor"],
      lanAddress: "192.168.42.12",
      overlayAddress: "10.77.0.12",
      apiPort: 8080,
      wireGuardListenPort: 51820,
      publicKeyEnv: "ALTIAIR_NODE_B_WG_PUBLIC_KEY",
      preferredLinks: ["wifi_ap", "wireguard_overlay", "ethernet"],
      capabilities: [
        {
          name: "sensor_ingest",
          detail: "Second independent camera, microphone, RFID, and heartbeat source.",
        },
        {
          name: "peer_relay",
          detail: "Emergency relay for compact bundles if the hub is unreachable.",
        },
      ],
      constraints: [
        "Do not block local capture on cloud or hub reachability.",
        "Retain audit metadata for duplicate and held bundles.",
      ],
      gatewayPriority: 5,
    },
    {
      id: "altiair-orin",
      hostname: "altiair-orin",
      platform: "jetson_orin_nano",
      roles: ["accelerated_inference", "foundry_gateway"],
      lanAddress: "192.168.42.20",
      overlayAddress: "10.77.0.20",
      apiPort: 8080,
      wireGuardListenPort: 51820,
      publicKeyEnv: "ALTIAIR_ORIN_WG_PUBLIC_KEY",
      preferredLinks: ["wifi_ap", "ethernet", "wireguard_overlay"],
      capabilities: [
        {
          name: "vision_inference",
          detail: "Accelerated local video/image inference and thumbnail generation.",
        },
        {
          name: "secondary_gateway",
          detail: "Secondary CASK/Foundry gateway when the Pi 5 hub is isolated or saturated.",
        },
      ],
      constraints: [
        "GPU inference must respect queue backpressure and thermal limits.",
        "Run adapter services in containers when practical for repeatable deployment.",
      ],
      gatewayPriority: 20,
    },
  ],
};

export const nominalMeshObservations: PeerObservation[] = [
  {
    nodeId: "altiair-hub",
    online: true,
    lastSeenSeconds: 1,
    linkClass: "ethernet",
    latencyMs: 8,
    packetLoss: 0.001,
    queueDepth: 12,
    inFlightTransfers: 1,
    cpuLoad: 0.38,
    memoryPressure: 0.42,
    internetReachable: true,
    foundryReachable: true,
    recentUploadSuccess: true,
    uplinkKbps: 9000,
    downlinkKbps: 21000,
  },
  {
    nodeId: "altiair-node-a",
    online: true,
    lastSeenSeconds: 2,
    linkClass: "wifi_ap",
    latencyMs: 19,
    packetLoss: 0.012,
    queueDepth: 43,
    inFlightTransfers: 1,
    cpuLoad: 0.55,
    memoryPressure: 0.5,
    internetReachable: false,
    foundryReachable: false,
    recentUploadSuccess: false,
    uplinkKbps: 1800,
    downlinkKbps: 2500,
  },
  {
    nodeId: "altiair-node-b",
    online: true,
    lastSeenSeconds: 3,
    linkClass: "wifi_ap",
    latencyMs: 24,
    packetLoss: 0.018,
    queueDepth: 36,
    inFlightTransfers: 0,
    cpuLoad: 0.49,
    memoryPressure: 0.48,
    internetReachable: false,
    foundryReachable: false,
    recentUploadSuccess: false,
    uplinkKbps: 1600,
    downlinkKbps: 2400,
  },
  {
    nodeId: "altiair-orin",
    online: true,
    lastSeenSeconds: 2,
    linkClass: "ethernet",
    latencyMs: 10,
    packetLoss: 0.002,
    queueDepth: 18,
    inFlightTransfers: 1,
    cpuLoad: 0.42,
    memoryPressure: 0.45,
    internetReachable: true,
    foundryReachable: true,
    recentUploadSuccess: true,
    uplinkKbps: 11000,
    downlinkKbps: 26000,
  },
];
